jira/examples/issue/delete/delete.go
jira/issue.go
jira/issue_test.go

:sparkles: Enabled to ability to delete an issue with a sub-tasks

---

jira/v2/filter.go
jira/v2/filter_test.go
jira/v3/filter.go
jira/v3/filter_test.go

1. Added the ability to change the filter owner.
2. https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-filters/#api-rest-api-3-filter-id-owner-put

:sparkles: Added the ability to change the filter owner.

---

pkg/infra/models/jira_dashboard.go

1. Added the editPermissions structure on the Dashboard update payload

:pencil2: Mapped the editPermissions

---

jira/mocks/get-permission-projects.json
jira/v2/issueTypeScreenScheme.go
jira/v2/issueTypeScreenScheme_test.go
jira/v2/permission.go
jira/v2/permission_test.go
jira/v3/issueTypeScreenScheme.go
jira/v3/issueTypeScreenScheme_test.go
jira/v3/permission.go
jira/v3/permission_test.go
pkg/infra/models/jira_issue_type_screen_scheme.go
pkg/infra/models/jira_permission.go
pkg/infra/models/jira_project.go

:sparkles: Mapped the Jira.Permission.Project method.

---

pkg/infra/models/jira_issue_type_screen_scheme.go

Reverts ctreminiom/go-atlassian#132

Revert ":recycle: Edited IssueTypeScreenSchemeMappingPayloadScheme"

---

pkg/infra/models/jira_issue_type_screen_scheme.go

1. Added the Description tag on the struct IssueTypeScreenSchemePayloadScheme
2. Closes #131

:recycle: Edited IssueTypeScreenSchemeMappingPayloadScheme

---

jira/v2/issueAttachment.go
jira/v2/issueAttachment_test.go
jira/v3/issueAttachment.go
jira/v3/issueAttachment_test.go

:sparkles: Mapped the Jira Issue Attachment Download method

---

jira/v2/issueField.go
jira/v2/issueField_test.go
jira/v3/issueField.go
jira/v3/issueField_test.go

1. Added the possibility to move customfield to the trash
2. Added the possibility to restore a customfield from the trash

:sparkles: Edited issueField.go

---

pkg/infra/models/jira_issue_v2.go
pkg/infra/models/jira_issue_v3.go

1. Mapped the Parent customfield struct

:building_construction: jira_issue_*.go edited

---

pkg/infra/models/jira_issue_v3.go

This exposes the attachments when retrieving the Issues

Add AttachmentScheme to IssueFieldsScheme

---

jira/internal/workflow_status_impl.go
jira/internal/workflow_status_impl_test.go
pkg/infra/models/jira_workflow_status.go
service/jira/workflow.go

:sparkles: Implemented the Workflow.Status.Bulk method

---

jira/internal/workflow_status_impl.go
jira/internal/workflow_status_impl_test.go
pkg/infra/models/errors.go
service/jira/workflow.go

1. Created a method called Get() under the WorkflowStatusConnector interface
2. Created a new implementation of the new interface method
3. Created a new dedicated error template

:sparkles: Added the get the workflow status by ID or Name

---

pkg/infra/models/jira_filter.go

1. Added the EditPermissions struct tag on the FilterPayloadScheme struct.
2. This change will grant the ability to modify the edit permissions on the filter creation.

:building_construction: Edited the FilterPayloadScheme

---

jira/internal/link_impl.go
jira/internal/link_impl_adf.go
jira/internal/link_impl_adf_test.go
jira/internal/link_impl_rich_text.go
jira/internal/link_impl_rich_text_test.go
jira/internal/link_impl_test.go
jira/internal/remote_link_impl.go
jira/internal/remote_link_impl_test.go
jira/v2/api_client_impl.go
jira/v3/api_client_impl.go
pkg/infra/models/errors.go
pkg/infra/models/jira_remote_links.go
service/jira/remoteLink.go

1. Added the possibility to extract the issue remote links
2. Documented the service methods on the documentation site.

:sparkles: Created the Jira Remote Link service.

---

jira/internal/announcement_banner_impl.go
jira/internal/announcement_banner_impl_test.go
jira/v2/api_client_impl.go
jira/v3/api_client_impl.go
pkg/infra/models/jira_announcement_banner.go
service/jira/announcement-banner.go

1. Added the possibility to interacts with the Jira banner using the v2 and v3 modules.
2. Resolves #149

:sparkles: Added the Jira Announcement Banner Service.

---

pkg/infra/models/jira_project.go

1. Added the possibility to set the structures schemes on the project creation.

:art: Edited the ProjectPayloadScheme struct

---

jira/internal/attachment_impl.go

Var should be passed as reference, to be filled with response data

Fix for issue 260

---

pkg/infra/models/jira_field.go
pkg/infra/models/jira_field_context_option.go
pkg/infra/models/jira_issue_custom_fields.go

Added custom field request type

---

jira/sm/internal/type_impl.go
pkg/infra/models/sm_request_type.go
service/sm/type.go

Implemented (Service Desk Get request type groups)[https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-servicedesk/#api-rest-servicedeskapi-servicedesk-servicedeskid-requesttypegroup-get]

Added service desk request type groups

---

jira/internal/issue_impl_adf_test.go
pkg/infra/models/jira_issue_v2.go
pkg/infra/models/jira_issue_v3.go

Based on the documenation `RenderedFields` is an Object, like `Fields`.
Maybe it makes sense to have a struct for that, but so far the possible content is not known to me.

Added RenderedFields and replaced string with time.Time in date fields

---

admin/internal/organization_impl.go
bitbucket/api_client_impl.go
bitbucket/api_client_impl_test.go
bitbucket/internal/authentication_impl.go
bitbucket/internal/workspace_impl.go
bitbucket/internal/workspace_impl_test.go
jira/agile/internal/sprint_impl_test.go
jira/internal/group_user_picker_impl.go
jira/internal/type_screen_scheme_impl_test.go
jira/internal/watcher_impl.go
jira/internal/worklog_impl_rich_text_test.go
pkg/infra/models/agile_sprint.go
pkg/infra/models/assets_object.go
pkg/infra/models/jira_field.go
pkg/infra/models/jira_time.go
service/confluence/analytics.go
service/jira/field-config.go
service/jira/task.go
service/sm/comment.go

Updated code style

---

pkg/infra/models/jira_project.go

1. Added the LeadAccountID tag under ProjectUpdateScheme.
2. Ordered the ProjectUpdateScheme struct tags.
3. Fixed #290

:art: jira_project.go edited.

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/lint.yml
.github/workflows/test.yml

This pull request updates several GitHub Actions workflows to improve compatibility and maintainability. The most important changes include upgrading the runner version, refining the event triggers, and updating the Go language versions in the matrix configurations.
* [`.github/workflows/codeql-analysis.yml`](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188L26-R26): Updated the runner version from `ubuntu-20.04` to `ubuntu-latest` to ensure the workflow uses the most up-to-date environment.
* [`.github/workflows/dependency-review.yml`](diffhunk://#diff-7cdd3ccec44c8ba176bdc3b9ef54c3f56aa210a1a4e2bb5f79d87b1e50314a18L8-R9): Refined the event trigger for `pull_request` by expanding it into a structured format, which allows for potential future customization. …

Fixed deprecated actions issue and update to 1.24 golang
