- confluence/confluence.go
- confluence/content.go
- confluence/contentRestriction.go
- confluence/contentRestrictionOperationGroup.go
- confluence/contentRestrictionOperationGroup_test.go
- confluence/contentRestriction_test.go
- confluence/contentRestrictionsOperation.go
- confluence/contentRestrictionsOperation_test.go
- confluence/mocks/get-content-restriction-by-operation.json
- confluence/mocks/get-content-restrictions.json
- go.mod
- go.sum
- pkg/infra/models/confluence_content.go
- pkg/infra/models/confluence_content_restriction.go
- pkg/infra/models/confluence_space.go
- pkg/infra/models/errors.go
1. Added the following method under *contentRestriction.go*
* Get restrictions
* Update restrictions
* Add restrictions
* Delete restrictions
2. Parsed the Content Restriction Operations
3. Parsed the Content Restriction Operation for groups.
4. Added the github.com/google/uuid library
> :sparkles: Added the Confluence Restriction Service

- jira/mocks/get-project-properties.json
- jira/mocks/get-project-property.json
- jira/v2/jira.go
- jira/v2/project.go
- jira/v2/projectProperty.go
- jira/v2/projectProperty_test.go
- jira/v3/jira.go
- jira/v3/project.go
- jira/v3/projectProperty.go
- jira/v3/projectProperty_test.go
- pkg/infra/models/errors.go
- pkg/infra/models/jira_project_property.go
1. Added the project property service on the Jira V2
> :sparkles: Added on the Project.Property service.

- confluence/confluence.go
- confluence/mocks/space-permission-v2.json
- confluence/space.go
- confluence/spacePermission.go
- confluence/spacePermission_test.go
- pkg/infra/models/confluence_content_permission.go
- pkg/infra/models/confluence_space_permission.go
1. Added the ability to manipulates the space permissions.
2. Added the Add, Bulk and Removes methods.
> :sparkles: Added the Space Permission service.

- .github/workflows/lint.yml
- jira/mocks/jira-issue-search-check.json
- jira/v2/issueSearch.go
- jira/v2/issueSearch_test.go
- jira/v3/issueSearch.go
- jira/v3/issueSearch_test.go
- pkg/infra/models/jira_issue_search.go
1. Added the Checks method under the IssueSearch service
2. https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-jql-match-post
> :sparkles: Mapped the Jira Issue Search endpoints

- pkg/infra/models/jira_issue_type_screen_scheme.go
1. Added the Description tag on the struct IssueTypeScreenSchemeMappingPayloadScheme
2. Closes #131
> :recycle: Edited IssueTypeScreenSchemeMappingPayloadScheme

- jira/internal/workflow_impl.go
- jira/internal/workflow_impl_test.go
- jira/internal/workflow_status_impl.go
- jira/internal/workflow_status_impl_test.go
- jira/v2/api_client_impl.go
- jira/v3/api_client_impl.go
- pkg/infra/models/errors.go
- pkg/infra/models/jira_workflow_status.go
- service/jira/workflow.go
1. Created the interface called WorkflowStatusConnector which contains the service contract.
2. Created the WorkflowStatusService struct with the service implementation under workflow_status_impl.go
3. Created the dedicated structs under jira_workflow_status.go
4. Injected the service implementation under the WorkflowService struct (Workflow.Status.*)
5. Created the Unit Test Cases with a 92.5% of coverage
6. Fixes #140
> :sparkles: Implemented the Workflow Status service.

- confluence/internal/search_impl.go
- confluence/internal/search_impl_test.go
The internal content search implementation currently does not propagate the "expand" option to the underlying query. This does not allow the user to pass that parameter in.
I adjusted the appropriate tests.
> Added the expand option to the internalSearch implementation for content

- confluence/api_client_impl.go
- confluence/internal/analytics_impl.go
- confluence/internal/analytics_impl_test.go
- pkg/infra/models/confluence_analytics.go
- service/confluence/analytics.go
1. Added the possibility to extract the content views using the id as reference.
2. Created the unit test cases with a 94% of coverage
3. Documented the service methods on the documentation site.
4. Closes #155
> :sparkles: Created the Analytics Confluence service.

- confluence/internal/space_v2_impl.go
- confluence/internal/space_v2_impl_test.go
- confluence/v2/api_client_impl.go
- pkg/infra/models/confluence_space_v2.go
- service/confluence/space.go
1. Added the possibility to extract the Confluence space information using the V2 API
2. Documented the service methods on the documentation site.
> :sparkles: Created the Confluence Space V2 service.

- admin/apl_client_impl.go
- admin/internal/organization_directory_impl.go
- admin/internal/organization_directory_impl_test.go
- admin/internal/organization_impl.go
- admin/internal/organization_impl_test.go
- pkg/infra/models/admin_organization.go
- service/admin/organization_directory.go
1. Added the ability to extract the last-activity information from an Atlassian Account using the id as reference.
2. Added the ability to suspend, enable and remove accounts.
> :sparkles: Implemented the Admin Cloud Organization Directory Service.

- jira/agile/internal/board_backlog_impl.go
- jira/internal/team_impl.go
- jira/internal/team_impl_test.go
- jira/v2/api_client_impl.go
- jira/v3/api_client_impl.go
- pkg/infra/models/jira_teams.go
- service/agile/backlog.go
- service/jira/team.go
1. Added the possibility to interacts with the Jira Roadmaps Teams and gets and creates teams on the Jira instance.
> :sparkles: Added the Jira Roadmaps Team service

- pkg/infra/models/jira_issue_custom_fields.go
- pkg/infra/models/jira_issue_custom_fields_test.go
It makes getting custom fields values which are from type string way easier to handle.
> Added ParseStringCustomField

- confluence/internal/page_impl.go
- confluence/internal/page_impl_test.go
- service/confluence/page.go
The Confluence V2 API Bulk get supports filtering by IDs and status. This adds
support for those and body-format in the form of an additional method `BulkFiltered()`.
Fixes #218.
> Add Support for Filtering Confluence V2 Bulk

- confluence/internal/page_impl.go
- confluence/internal/page_impl_test.go
- pkg/infra/models/confluence_page.go
- service/confluence/page.go
1. Created a method called Gets() under the PageConnector interface
2. Deprecated the Bulk() method because the Gets() method enables the possibility to set filter criteria.
3. Removed the BulkFiltered() method
4. Added the Unit Test Cases with a 95% of coverage.
> :sparkles: Added the Page.Gets() method on the Confluence V2 module

- bitbucket/api_client_impl.go
- bitbucket/api_client_impl_test.go
- bitbucket/internal/authentication_impl.go
- bitbucket/internal/authentication_impl_test.go
- bitbucket/internal/workspace_impl.go
- bitbucket/internal/workspace_impl_test.go
- bitbucket/internal/workspace_permissions_impl.go
- bitbucket/internal/workspace_permissions_impl_test.go
- bitbucket/internal/workspace_webhooks_impl.go
- bitbucket/internal/workspace_webhooks_impl_test.go
- pkg/infra/models/bitbucket_branch.go
- pkg/infra/models/bitbucket_projects.go
- pkg/infra/models/bitbucket_repository.go
- pkg/infra/models/bitbucket_webhooks.go
- pkg/infra/models/bitbucket_workspace.go
- pkg/infra/models/bitbucket_workspace_membership.go
- pkg/infra/models/errors.go
- service/bitbucket/workspace.go
1. Created a new module called bitbucket.
2. It enables the possibility to interact with the Bitbucket Cloud V2 API.
3. Created the Workspace interfaces.
> :sparkles: Added the Bitbucket Workspace implementation.

- jira/sm/internal/request_impl.go
- jira/sm/internal/request_impl_test.go
- pkg/infra/models/errors.go
- pkg/infra/models/sm_request_field.go
- pkg/infra/models/sm_request_field_test.go
- service/sm/request.go
1. Removed the necessity to use two struct when you want to create a new ITSM request.
2. The CreateCustomerRequestPayloadScheme contains multiple methods to inject the customfields based on the field type.
3. Added the possibility to embed form on the CreateCustomerRequestPayloadScheme struct.
4. Added the IsAdfRequest and RaiseOnBehalfOf tags on the CreateCustomerRequestPayloadScheme struct.
5. Changed the RequestConnector.Create method contract removing the CustomerRequestFields struct.
6. Added the new customfield handling implementation with a 100% of coverage.
> :boom: Improved the SM.Request.Create() method.

- confluence/internal/space_v2_impl_test.go
- pkg/infra/models/confluence_space_v2.go
Fixes #240 by addressing the following two discrepancies between Confluence Space V2 API's Get Method return values and `SpaceSchemaV2`'s member types':
- Confluence Space V2 API Returns HomepageID As String
- Confluence Space V2 API Returns ID As String
> Fix Issue #240: Adjust SpaceSchemeV2 `id` & `homepageID` Types

- assets/internal/object_type_attribute_impl.go
- assets/internal/object_type_attribute_impl_test.go
- pkg/infra/models/assets_object.go
- service/assets/object_type_attribute.go
Hello,
Like explain here : https://developer.atlassian.com/cloud/assets/rest/api-group-objecttypeattribute/#api-objecttypeattribute-objecttypeid-post, the type of the payload of the objecttypeattribute is not an ObjectTypeAttribute object.
In fact, for the creation of an attribute with the type 0 (default type), we need to fill the defaultTypeId parameter.
This parameter is missing in the objectTypeAttribute object.
> Add ObjectTypeAttribute Payload for the creation and the update of the Assets Object Type Attribute

- jira/sm/internal/customer_impl.go
- jira/sm/internal/customer_impl_test.go
- service/sm/customer.go
Based on the official document those URLs wants a string for `serviceDeskID`.
https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-servicedesk/#api-rest-servicedeskapi-servicedesk-servicedeskid-customer-get
This will be a breaking change.
> Replace service desk id with string instead of int

- pkg/infra/models/sm_request_type.go
https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-servicedesk/#api-rest-servicedeskapi-servicedesk-servicedeskid-requesttype-requesttypeid-field-get
This will be a breaking change
> Fixed struct types and added missing properties in request type fields

- pkg/infra/models/errors.go
- pkg/infra/models/jira_field.go
- pkg/infra/models/jira_issue_custom_fields_tempo.go
- pkg/infra/models/jira_issue_custom_fields_tempo_test.go
- pkg/infra/models/jira_issue_custom_fields_test.go
This allowes parsing the custom field account from the jira plugin Tempo.
Which is one of the build in provided custom fields.
> Added parse function for tempo account

- jira/internal/issue_impl_adf.go
1. Fixed the Issue.Created() method when the customfield struct is provided without any fields.
2. Relates to #300 
3. Refactored the method implementation
> :bug: issue_impl_adf.go edited

- confluence/internal/page_impl_test.go
- pkg/infra/models/confluence_page.go
This pull request includes updates to the `pkg/infra/models/confluence_page.go` file to enhance the Confluence page model by adding new fields and changing data types. The most important changes involve adding `ParentID` and `OwnerID` fields and changing the data type of `ID` and `SpaceID` from `int` to `string`.
* [`pkg/infra/models/confluence_page.go`](diffhunk://#diff-84a013dbada8ba18ef8d89eb0e5bddb22f56cea72bae4bf829b99934b7c75463R79): Added `ParentID` field to `PageCreatePayloadScheme` to store the ID of the parent page.
* [`pkg/infra/models/confluence_page.go`](diffhunk://#diff-84a013dbada8ba18ef8d89eb0e5bddb22f56cea72bae4bf829b99934b7c75463L90-R96): Changed the data type of `ID` and `SpaceID` from `int` to `string` in `PageUpdatePayloadScheme` for consistency and flexibility.
* …
> Changed data type to match other docs and added missing fields

- README.md
- jira/internal/metadata_impl.go
- jira/internal/metadata_impl_test.go
- service/jira/metadata.go
- Resolves: #319
- Updated the README.md and added a new section to execute a RAW endpoints
> :sparkles: Mapped the new issue.Metadata methods.

- jira/internal/issue_impl_adf.go
- jira/internal/issue_impl_adf_test.go
- jira/internal/issue_impl_rich_text.go
- jira/internal/issue_impl_rich_text_test.go
- pkg/infra/models/jira_issue_v2.go
- pkg/infra/models/jira_issue_v2_test.go
- pkg/infra/models/jira_issue_v3.go
- pkg/infra/models/jira_issue_v3_test.go
- pkg/infra/models/jira_resolution.go
@breathingdust the `transitionID` field was not correctly injected during payload generation using the mergo library. This caused the following error:
```bash
2024/10/05 21:51:20 {"errorMessages":["Missing 'transition' identifier"],"errors":{}}
```
Additionally, when the `ResolutionScheme` was set in the struct, the fields ID, Name, and Description were being added incorrectly due to the absence of the `omitempty` tag.
Resolves #318
- Please make sure the `Resolution` field is added on the screen scheme configuration linked on the issuetype.
```json
{
"errorMessages": [],
"errors": {
"resolution": "Field 'resolution' cannot be set. It is not on the appropriate screen, or unknown."
}
}
```
- If the status transition is linked to a screen, the Resolution field must be included; otherwise, …
> :bug: Fixed the Issue.Move() field injection

- .github/workflows/coverage.yml
This pull request includes a change to the Go setup in the GitHub Actions workflow for code coverage. The most important change is:
* [`.github/workflows/coverage.yml`](diffhunk://#diff-a2115d277b5ca5a2f09a999e53440839cf332b94da177f3d1766334555b0f7c6L21-R21): Modified the Go setup to use the `go-version-file` from `./go.mod` instead of specifying a fixed Go version.
> use same version for coverage as tracked in repository

- jira/internal/watcher_impl.go
- jira/internal/watcher_impl_test.go
Currently, when creating a Jira "Add Watcher" request, the username in playload has been converted from a `string` type to a `[]byte` type. This change causes the JSON-encoded result is not the username, leading to request failure. Here’s an example. https://go.dev/play/p/pBiwq2t2bNl
```golang
package main
import (
"bytes"
"encoding/json"
"fmt"
)
func main() {
accountID := "someuser"
buf1 := new(bytes.Buffer)
if err := json.NewEncoder(buf1).Encode(accountID); err != nil {
panic(err)
}
fmt.Println(buf1)
buf2 := new(bytes.Buffer)
if err := json.NewEncoder(buf2).Encode([]byte(accountID)); err != nil {
panic(err)
}
fmt.Println(buf2)
}
```
output
```
"someuser"
"c29tZXVzZXI="
```
> Fix add watcher invalid payload issue

- jira/internal/issue_archive_impl.go
- jira/internal/issue_archive_impl_test.go
- jira/v2/api_client_impl.go
- jira/v3/api_client_impl.go
- pkg/infra/models/issue_archival.go
- service/jira/archive.go
Resolves #339
Documentation created: https://docs.go-atlassian.io/jira-software-cloud/issues/archiving
> :sparkles: Added the Issue Archiving API

- jira/internal/search_impl_adf.go
- jira/internal/search_impl_adf_test.go
- jira/internal/search_impl_rich_text.go
- jira/internal/search_impl_rich_text_test.go
- pkg/infra/models/jira_search_count.go
- pkg/infra/models/jira_search_v2.go
- pkg/infra/models/jira_search_v3.go
- service/jira/search.go
This pull request introduces significant updates to the Jira search services by deprecating older endpoints and adding support for newer ones, including JQL-based search, approximate issue count, and bulk issue fetching. The changes also include updates to the internal implementations and data models to support these new functionalities.
* **Deprecation of Legacy Endpoints**: Marked the `Get` and `Post` methods in both `SearchADFService` and `SearchRichTextService` as deprecated, with a note that these will be removed after May 1, 2025. Users are encouraged to use the new `SearchJQL`, `BulkFetch`, and `ApproximateCount` methods instead. (`jira/internal/search_impl_adf.go`: [[1]](diffhunk://#diff-5bf058e6cede7f34d445fa1d2c4b6ef232123e7db2798c6b5422cf5a985df330R36-R37) …
> Added new jql search and marked old functions as deprecated

- .codacy.yml
- README.md
This pull request updates the `.codacy.yml` configuration file to customize linting rules for the project. The changes introduce exclusions for specific rules in `revive` and `markdownlint` tools.
Linting configuration updates:
* Added a `tools` section to enable `revive` and `markdownlint` with specific rules ignored:
- [`revive`](diffhunk://#diff-6e27af35533eda2e3e82d6d7f8654c26824396797716d37ac7df096a1b090503R4-R14): Ignored the `Revive_package-comments` rule to bypass package comment checks.
- [`markdownlint`](diffhunk://#diff-6e27af35533eda2e3e82d6d7f8654c26824396797716d37ac7df096a1b090503R4-R14): Ignored the `markdownlint_MD013` rule to disable the line length restriction.
> Ignore package comments and markdown length limit

- assets/internal/aql_impl_test.go
- pkg/infra/models/assets_aql.go
This pull request updates the `IncludeAttributesDeep` field in the AQL implementation to change its type from `bool` to `int`, reflecting a shift in how attribute depth is handled. Corresponding test cases and request logic have been updated to align with this change.
* [`pkg/infra/models/assets_aql.go`](diffhunk://#diff-aa615e70b3a53db3f7e9ae19c215a5d8e0564f7b3ec7829c625b411a005bcc86L20-R20): Changed the type of the `IncludeAttributesDeep` field in the `AQLSearchParamsScheme` struct from `bool` to `int`. This allows specifying the depth of attributes as an integer rather than a boolean.
* [`assets/internal/aql_impl_test.go`](diffhunk://#diff-677f8f00b4af10ff25bc2a96bb2cb9ccae6c60e6bcc84ed75649bf88d9e73ec7L21-R22): Updated test cases in `Test_internalAQLImpl_Filter` to reflect the type …
> 🐛 Fixed Assets IncludeAttributesDeep type

- .github/workflows/codacy.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/dependency-review.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
This pull request updates several GitHub Actions workflows to pin specific commit SHAs for the actions used, ensuring reproducibility and security. The changes affect multiple workflows, including Codacy, CodeQL analysis, coverage, dependency review, linting, and testing.
* **`actions/checkout`**: Updated to commit `11bd71901bbe5b1630ceea73d27597364c9af683` across all workflows, replacing the generic `v4` tag. [[1]](diffhunk://#diff-f0d3530b5eea10fe26ad541e683cfb4072e290804705de6abf6a5b2e80a72f59L39-R39) [[2]](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188L38-R42) [[3]](diffhunk://#diff-a2115d277b5ca5a2f09a999e53440839cf332b94da177f3d1766334555b0f7c6L14-R19) [[4]](diffhunk://#diff-7cdd3ccec44c8ba176bdc3b9ef54c3f56aa210a1a4e2bb5f79d87b1e50314a18L19-R21) …
> 💚 Pin github actions via sha

- jira/internal/myself_impl.go
- jira/internal/myself_impl_test.go
- pkg/infra/models/errors.go
- service/jira/myself.go
This pull request introduces new functionality for managing user preferences in the Jira API client. It adds methods to retrieve, set, and delete user preferences, along with the necessary infrastructure to support these operations.
* **Added methods in `MySelfService` for user preferences:**
- Introduced `Get`, `Set`, and `Delete` methods to retrieve, update, and delete user preferences, respectively. These methods are implemented in both the `MySelfService` interface and its internal implementation (`internalMySelfImpl`). [[1]](diffhunk://#diff-8d49505c63afe44de6ef78ffd2d661231e59a55650494c89efb6db0c0c0845c1R42-R68) [[2]](diffhunk://#diff-8d49505c63afe44de6ef78ffd2d661231e59a55650494c89efb6db0c0c0845c1R100-R183) [[3]](diffhunk://#diff-d4efa443c7561297409b1d70c846109d9a13634afcbf942a76838 …
> ✨ Added mypreferences

- pkg/infra/models/jira_user.go
This pull request introduces a new set of constants to represent different user account types in the `pkg/infra/models/jira_user.go` file. These constants will help standardize the representation of user account types in the codebase.
Key change:
* [`pkg/infra/models/jira_user.go`](diffhunk://#diff-71bb2403369d798e2bca5220d01b2c13a3de44b1ddc8088b20b288bf29d3a33cR3-R10): Added constants `UserAccountTypeAtlassian`, `UserAccountTypeApp`, `UserAccountTypeCustomer`, and `UserAccountTypeUnknown` to define user account types in Jira.
> Added predefine account types

- jira/internal/issue_impl_adf.go
- jira/internal/issue_impl_rich_text.go
- jira/internal/metadata_impl.go
- jira/internal/priority_impl.go
- jira/internal/project_impl.go
- jira/internal/search_impl_adf.go
- jira/internal/search_impl_rich_text.go
- pkg/infra/models/jira_changelog.go
- pkg/infra/models/jira_comment_v2.go
- pkg/infra/models/jira_comment_v3.go
- pkg/infra/models/jira_issue_attachments.go
- service/jira/metadata.go
- service/jira/priority.go
This pull request includes several updates to the Jira API client to address deprecated endpoints, missing parameters, and data type improvements. These changes primarily involve adding TODO comments to document areas for future improvement while maintaining backward compatibility in the current version. Below is a summary of the most important changes grouped by theme:
* Added deprecation notices for the `Get` and `Post` methods in `SearchADFService` and `SearchRichTextService`, as these endpoints are scheduled for removal after May 1, 2025. Suggested alternatives include `SearchJQL`, `BulkFetch`, and `ApproximateCount` methods. [[1]](diffhunk://#diff-5bf058e6cede7f34d445fa1d2c4b6ef232123e7db2798c6b5422cf5a985df330R38) [[2]](diffhunk://#diff-5bf058e6cede7f34d445fa1d2c4b6ef232123e7db2798c6 …
> Added documentation about deprecations

- jira/internal/project_component_impl.go
- Fixes #400 where `Project.Component.Gets()` was always returning nil even when components exist
- The issue was caused by passing the slice by value instead of by reference to the `Call` method
The `Gets` method was calling `i.c.Call(request, components)` instead of `i.c.Call(request, &components)`. This caused JSON unmarshaling to fail silently, leaving the slice as nil.
Changed line 124 in `jira/internal/project_component_impl.go`:
```diff
- response, err := i.c.Call(request, components)
+ response, err := i.c.Call(request, &components)
```
This is a minimal fix that addresses the immediate issue. The same pattern is used correctly in 30+ other places in the codebase (e.g., `project_category_impl.go:91`, `workflow_status_impl.go:142`, etc.).
> fix: Project.Component.Gets always returns nil (#400)

- jira/internal/filter_impl.go
- jira/internal/filter_impl_test.go
- jira/internal/filter_share_impl.go
- jira/internal/filter_share_impl_test.go
- Fixes 4 additional instances of the same bug pattern as #400
- Slices were being passed by value instead of by reference to the `Call` method
Fixed the following methods that were returning nil due to missing `&` operator:
- `Favorite()` method (line 148) - `Call(request, filters)` → `Call(request, &filters)`  
- `My()` method (line 173) - `Call(request, filters)` → `Call(request, &filters)`
- `Gets()` method (line 148) - `Call(request, filters)` → `Call(request, &filters)`
- `Add()` method (line 170) - `Call(request, permissions)` → `Call(request, &permissions)`
Same as #400 - the slices were passed by value instead of by reference, causing JSON unmarshaling to fail silently and leave the slices as nil.
- Follows up on PR #401 which fixed the same issue in `Project.Component.Gets()`
- …
> fix: pass pointers to slices in Call methods for filter operations
